### ISSUE TITLE
怎么启动后台服务celery的是有用如下错误呢？我用的Python2.5.7

### ISSUE THREAD

**Issue by wang1980** [hanson007/FirstBlood#7]
Traceback (most recent call last):
  File "/data/FirstBlood-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 11, in <module>
    class Command(CeleryCommand):
  File "/usr/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 23, in Command
    preload_options)
TypeError: can only concatenate list (not "tuple") to list

**Comment by jimmy-bj** [comment]
> 
> 
> Traceback (most recent call last):
> File "/data/FirstBlood-master/manage.py", line 10, in
> execute_from_command_line(sys.argv)
> File "/usr/lib/python2.7/site-packages/django/core/management/**init**.py", line 364, in execute_from_command_line
> utility.execute()
> File "/usr/lib/python2.7/site-packages/django/core/management/**init**.py", line 356, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "/usr/lib/python2.7/site-packages/django/core/management/**init**.py", line 206, in fetch_command
> klass = load_command_class(app_name, subcommand)
> File "/usr/lib/python2.7/site-packages/django/core/management/**init**.py", line 40, in load_command_class
> module = import_module('%s.management.commands.%s' % (app_name, name))
> File "/usr/lib64/python2.7/importlib/**init**.py", line 37, in import_module
> **import**(name)
> File "/usr/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 11, in
> class Command(CeleryCommand):
> File "/usr/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 23, in Command
> preload_options)
> TypeError: can only concatenate list (not "tuple") to list

检查一下你pytyon加载的模块版本是否与requirements.txt中
提到的一致。
